-- liquibase formatted sql

-- changeset yofuj:1777829208355-1
CREATE TABLE otp_code
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code         VARCHAR(255),
    status       VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    expires_at   TIMESTAMP WITHOUT TIME ZONE,
    operation_id VARCHAR(255),
    user_id      UUID,
    CONSTRAINT pk_otp_code PRIMARY KEY (id)
);

-- changeset yofuj:1777829208355-2
CREATE TABLE otp_config
(
    id          BIGINT NOT NULL,
    code_length INTEGER,
    ttl_seconds INTEGER,
    CONSTRAINT pk_otp_config PRIMARY KEY (id)
);

-- changeset yofuj:1777829208355-3
CREATE TABLE users
(
    id       UUID NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset yofuj:1777829208355-4
ALTER TABLE otp_code
    ADD CONSTRAINT FK_OTP_CODE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

